### ISSUE TITLE
Doxygen 1.8.9.1 で動作しない

### ISSUE THREAD

**Issue by NAKADANobuhiro** [mima3/VbaDoxygen#1]
すばらしいソフトウェアをありがとうございます。
しかし、私の環境では Filter の問題か、Sample.xlsm であっても HTML にドキュメントが出力されません。(テンプレートは出力されるが、関数やソースのコメントが出力されない。)

ソースの抽出は成功しているため、vbfilter.exe を手動実行してソースを .cpp に変換し、それを src ディレクトリに配置、doxygen ファイルの FILE_PATTERNS = *.cpp と INPUT_FILTER  = として、Doxywizard を実行したところ、正しく HTML が出力されました。
よって、Doxygenとフィルターの組み合わせが原因に思えるのですが...

Doxygen は、1.8.9.1 です。

**Comment by mima3** [comment]
バグ報告ありがとうございます。

http://sourceforge.net/projects/doxygen/files/?source=navbar
Doxygenのrel-1.8.8からご指摘の事象が発生しています。

現在、回避方法を模索中です。

**Comment by NAKADANobuhiro** [comment]
早速の回答ありがとうございます。
それでは、rel-1.8.7 以前を使うというのも回避方法なのですね。
あとで試してみます。

**Comment by mima3** [comment]
修正しました。
当方の環境では、1.8.9.1でも動作するようになったのでご確認ください。

原因：
1.8.8より、Doxygenが認識しない拡張子の解析処理がスキップされるようになった。
https://github.com/doxygen/doxygen/commit/0dd59398b3f62288897c8c3405977a27a94fbfee

対策：
frm,cls,basの各拡張子において、C＋＋として処理するように、EXTENSION_MAPPINGを用いて明示するようにする。

**Comment by mima3** [comment]
修正箇所
https://github.com/mima3/VbaDoxygen/commit/2510e26dbdc3edeee98c46cafce8b9a48a32c235

**Comment by NAKADANobuhiro** [comment]
素晴らしい!!
見事に動作しました。
これからも愛用させていただきます。

**Comment by mima3** [comment]
動作確認ありがとうございました。
